/*
 * map.h
 *
 *  Created on: Jan 5, 2019
 *      Author: Ahmed Hessien
 */

#ifndef REGISTER_MAP_H_
#define REGISTER_MAP_H_

#include "std_types.h"

#define REG_SREG    *((volatile uint8 *)0x5F)
#define BIT_I       (7)
#define BIT_T       (6)
#define BIT_H       (5)
#define BIT_S       (4)
#define BIT_V       (3)
#define BIT_N       (2)
#define BIT_Z       (1)
#define BIT_C       (0)

#define REG_SPH     *((volatile uint8 *)0x5E)
#define REG_SPL     *((volatile uint8 *)0x5D)

#define REG_OCR0    *((volatile uint8 *)0x5C)

#define REG_GICR    *((volatile uint8 *)0x5B)
#define BIT_INT1    (7)
#define BIT_INT0    (6)
#define BIT_INT2    (5)
#define BIT_IVSEL   (1)
#define BIT_IVCE    (0)

#define REG_GIFR    *((volatile uint8 *)0x5A)
#define BIT_INTF1   (7)
#define BIT_INTF0   (6)
#define BIT_INTF2   (5)

#define REG_TIMSK   *((volatile uint8 *)0x59)
#define BIT_OCIE2   (7)
#define BIT_TOIE2   (6)
#define BIT_TICIE1  (5)
#define BIT_OCIE1A  (4)
#define BIT_OCIE1B  (3)
#define BIT_TOIE1   (2)
#define BIT_OCIE0   (1)
#define BIT_TOIE0   (0)


#define REG_TIFR    *((volatile uint8 *)0x58)
#define BIT_OCF2    (7)
#define BIT_TOV2    (6)
#define BIT_ICF1    (5)
#define BIT_OCF1A   (4)
#define BIT_OCF1B   (3)
#define BIT_TOV1    (2)
#define BIT_OCF0    (1)
#define BIT_TOV0    (0)

#define REG_SPMCR   *((volatile uint8 *)0x57)
#define BIT_SPMIE   (7)
#define BIT_RWWSB   (6)
#define BIT_RWWSRE  (4)
#define BIT_BLBSET  (3)
#define BIT_PGWRT   (2)
#define BIT_PGERS   (1)
#define BIT_SPMEN   (0)



#define REG_TWCR    *((volatile uint8 *)0x56)
#define BIT_TWINT   (7)
#define BIT_TWEA    (6)
#define BIT_TWSTA   (5)
#define BIT_TWSTO   (4)
#define BIT_TWWC    (3)
#define BIT_TWEN    (2)
#define BIT_TWIE    (0)

#define REG_MCUCR   *((volatile uint8 *)0x55)
#define BIT_SE      (7)
#define BIT_SM2     (6)
#define BIT_SM1     (5)
#define BIT_SM0     (4)
#define BIT_ISC11   (3)
#define BIT_ISC10   (2)
#define BIT_ISC01   (1)
#define BIT_ISC00   (0)


#define REG_MCUCSR  *((volatile uint8 *)0x54)
#define BIT_JTD     (7)
#define BIT_ISC2    (6)
#define BIT_JTRF    (4)
#define BIT_WDRF    (3)
#define BIT_BORF    (2)
#define BIT_EXTRF   (1)
#define BIT_PORF    (0)

#define REG_TCCR0   *((volatile uint8 *)0x53)
#define BIT_FOC0    (7)
#define BIT_WGM00   (6)
#define BIT_COM01   (5)
#define BIT_COM00   (4)
#define BIT_WGM01   (3)
#define BIT_CS02    (2)
#define BIT_CS01    (1)
#define BIT_CS00    (0)

#define REG_TCNT0   *((volatile uint8 *)0x52)

#define REG_OSCCAL  *((volatile uint8 *)0x51)
#define REG_OCDR    *((volatile uint8 *)0x51)

#define REG_SFIOR   *((volatile uint8 *)0x50)
#define BIT_ADTS2   (7)
#define BIT_ADTS1   (6)
#define BIT_ADTS0   (5)
#define BIT_ACME    (3)
#define BIT_PUD     (2)
#define BIT_PSR2    (1)
#define BIT_PSR10   (0)

#define REG_TCCR1A  *((volatile uint8 *)0x4F)
#define BIT_COM1A1  (7)
#define BIT_COM1A0  (6)
#define BIT_COM1B1  (5)
#define BIT_COM1B0  (4)
#define BIT_FOC1A   (3)
#define BIT_FOC1B   (2)
#define BIT_WGM11   (1)
#define BIT_WGM10   (0)

#define REG_TCCR1B  *((volatile uint8 *)0x4E)
#define BIT_ICNC1   (7)
#define BIT_ICES1   (6)
#define BIT_WGM13   (4)
#define BIT_WGM12   (3)
#define BIT_CS12    (2)
#define BIT_CS11    (1)
#define BIT_CS10    (0)

#define REG_TCNT1H  *((volatile uint8 *)0x4D)
#define REG_TCNT1L  *((volatile uint8 *)0x4C)
#define REG_OCR1AH  *((volatile uint8 *)0x4B)
#define REG_OCR1AL  *((volatile uint8 *)0x4A)
#define REG_OCR1BH  *((volatile uint8 *)0x49)
#define REG_OCR1BL  *((volatile uint8 *)0x48)
#define REG_ICR1H   *((volatile uint8 *)0x47)
#define REG_ICR1L   *((volatile uint8 *)0x46)

#define REG_TCCR2   *((volatile uint8 *)0x45)
#define BIT_FOC2    (7)  
#define BIT_WGM20   (6) 
#define BIT_COM21   (5) 
#define BIT_COM20   (4) 
#define BIT_WGM21   (3) 
#define BIT_CS22    (2)
#define BIT_CS21    (1)
#define BIT_CS20    (0)

#define REG_TCNT2   *((volatile uint8 *)0x44)

#define REG_OCR2    *((volatile uint8 *)0x43)

#define REG_ASSR    *((volatile uint8 *)0x42)
#define BIT_AS2     (3)
#define BIT_TCN2UB  (2) 
#define BIT_OCR2UB  (1) 
#define BIT_TCR2UB  (0)

#define REG_WDTCR   *((volatile uint8 *)0x41)
#define BIT_WDTOE   (4)
#define BIT_WDE     (3)
#define BIT_WDP2    (2)
#define BIT_WDP1    (1)
#define BIT_WDP0    (0)


#define REG_UBRRH   *((volatile uint8 *)0x40)
#define BIT_URSEL   (7)

#define REG_UCSRC   *((volatile uint8 *)0x40)
#define BIT_URSEL   (7)
#define BIT_UMSEL   (6)
#define BIT_UPM1    (5)
#define BIT_UPM0    (4)
#define BIT_USBS    (3)
#define BIT_UCSZ1   (2)
#define BIT_UCSZ0   (1)
#define BIT_UCPOL   (0)

#define REG_EEARH   *((volatile uint8 *)0x3F)
#define REG_EEARL   *((volatile uint8 *)0x3E)

#define REG_EEDR    *((volatile uint8 *)0x3D)

#define REG_EECR    *((volatile uint8 *)0x3C)
#define BIT_EERIE   (3)
#define BIT_EEMWE   (2)
#define BIT_EEWE    (1)
#define BIT_EERE    (0)

#define REG_PORTA *((volatile uint8 *)0x3B)
#define BIT_PORTA7  (7)
#define BIT_PORTA6  (6)
#define BIT_PORTA5  (5)
#define BIT_PORTA4  (4)
#define BIT_PORTA3  (3)
#define BIT_PORTA2  (2)
#define BIT_PORTA1  (1)
#define BIT_PORTA0  (0)


#define REG_DDRA *((volatile uint8 *)0x3A)
#define BIT_DDA7    (7)
#define BIT_DDA6    (6)
#define BIT_DDA5    (5)
#define BIT_DDA4    (4)
#define BIT_DDA3    (3)
#define BIT_DDA2    (2)
#define BIT_DDA1    (1)
#define BIT_DDA0    (0)

#define REG_PINA	*((volatile uint8*)0x39)
#define BIT_PINA7   (7)
#define BIT_PINA6   (6)
#define BIT_PINA5   (5)
#define BIT_PINA4   (4)
#define BIT_PINA3   (3)
#define BIT_PINA2   (2)
#define BIT_PINA1   (1)
#define BIT_PINA0   (0)

#define REG_PORTB *((volatile uint8 *)0x38)
#define BIT_PORTB7 (7)
#define BIT_PORTB6 (6)
#define BIT_PORTB5 (5)
#define BIT_PORTB4 (4)
#define BIT_PORTB3 (3)
#define BIT_PORTB2 (2)
#define BIT_PORTB1 (1)
#define BIT_PORTB0 (0)

#define REG_DDRB *((volatile uint8 *)0x37)
#define BIT_DDB7 (7)
#define BIT_DDB6 (6)
#define BIT_DDB5 (5)
#define BIT_DDB4 (4)
#define BIT_DDB3 (3)
#define BIT_DDB2 (2)
#define BIT_DDB1 (1)
#define BIT_DDB0 (0)

#define REG_PINB *((volatile uint8 *)0x36)
#define BIT_PINB7 (7)
#define BIT_PINB6 (6)
#define BIT_PINB5 (5)
#define BIT_PINB4 (4)
#define BIT_PINB3 (3)
#define BIT_PINB2 (2)
#define BIT_PINB1 (1)
#define BIT_PINB0 (0)

#define REG_PORTC *((volatile uint8 *)0x35)
#define BIT_PORTC7 (7)
#define BIT_PORTC6 (6)
#define BIT_PORTC5 (5)
#define BIT_PORTC4 (4)
#define BIT_PORTC3 (3)
#define BIT_PORTC2 (2)
#define BIT_PORTC1 (1)
#define BIT_PORTC0 (0)

#define REG_DDRC *((volatile uint8 *)0x34)
#define BIT_DDC7 (7)
#define BIT_DDC6 (6)
#define BIT_DDC5 (5)
#define BIT_DDC4 (4)
#define BIT_DDC3 (3)
#define BIT_DDC2 (2)
#define BIT_DDC1 (1)
#define BIT_DDC0 (0)

#define REG_PINC *((volatile uint8 *)0x33)
#define BIT_PINC7 (7)
#define BIT_PINC6 (6)
#define BIT_PINC5 (5)
#define BIT_PINC4 (4)
#define BIT_PINC3 (3)
#define BIT_PINC2 (2)
#define BIT_PINC1 (1)
#define BIT_PINC0 (0)

#define REG_PORTD *((volatile uint8 *)0x32)
#define BIT_PORTD7 (7)
#define BIT_PORTD6 (6)
#define BIT_PORTD5 (5)
#define BIT_PORTD4 (4)
#define BIT_PORTD3 (3)
#define BIT_PORTD2 (2)
#define BIT_PORTD1 (1)
#define BIT_PORTD0 (0)

#define REG_DDRD *((volatile uint8 *)0x31)
#define BIT_DDD7 (7)
#define BIT_DDD6 (6)
#define BIT_DDD5 (5)
#define BIT_DDD4 (4)
#define BIT_DDD3 (3)
#define BIT_DDD2 (2)
#define BIT_DDD1 (1)
#define BIT_DDD0 (0)

#define REG_PIND    *((volatile uint8 *)0x30)
#define BIT_PIND7 (7)
#define BIT_PIND6 (6)
#define BIT_PIND5 (5)
#define BIT_PIND4 (4)
#define BIT_PIND3 (3)
#define BIT_PIND2 (2)
#define BIT_PIND1 (1)
#define BIT_PIND0 (0)

#define REG_SPDR *((volatile uint8 *)0x2F)

#define REG_SPSR *((volatile uint8 *)0x2E)
#define BIT_SPIF    (7)
#define BIT_WCOL    (6)
#define BIT_SPI2X   (0)

#define REG_SPCR    *((volatile uint8 *)0x2D)
#define BIT_SPIE    (7) 
#define BIT_SPE     (6)
#define BIT_DORD    (5) 
#define BIT_MSTR    (4) 
#define BIT_CPOL    (3) 
#define BIT_CPHA    (2) 
#define BIT_SPR1    (1) 
#define BIT_SPR0    (0)

#define REG_UDR    *((volatile uint8 *)0x2C)

#define REG_UCSRA    *((volatile uint8 *)0x2B)
#define BIT_RXC     (7)
#define BIT_TXC     (6) 
#define BIT_UDRE    (5) 
#define BIT_FE      (4) 
#define BIT_DOR     (3) 
#define BIT_PE      (2) 
#define BIT_U2X     (1) 
#define BIT_MPCM    (0) 

#define REG_UCSRB    *((volatile uint8 *)0x2A)
#define BIT_RXCIE   (7)
#define BIT_TXCIE   (6)
#define BIT_UDRIE   (5)
#define BIT_RXEN    (4)
#define BIT_TXEN    (3)
#define BIT_UCSZ2   (2)
#define BIT_RXB8    (1)
#define BIT_TXB8    (0)

#define REG_UBRRL    *((volatile uint8 *)0x29)

#define REG_ACSR *((volatile uint8 *)0x28)
#define BIT_ACD     (7)
#define BIT_ACBG    (6)
#define BIT_ACO     (5)
#define BIT_ACI     (4)
#define BIT_ACIE    (3)
#define BIT_ACIC    (2)
#define BIT_ACIS1   (1) 
#define BIT_ACIS0   (0)

#define REG_ADMUX    *((volatile uint8 *)0x27)
#define BIT_REFS1   (7)
#define BIT_REFS0   (6)
#define BIT_ADLAR   (5)
#define BIT_MUX4    (4)
#define BIT_MUX3    (3)
#define BIT_MUX2    (2)
#define BIT_MUX1    (1)
#define BIT_MUX0    (0)
 
#define REG_ADCSRA     *((volatile uint8 *)0x26)
#define BIT_ADEN    (7)
#define BIT_ADSC    (6)
#define BIT_ADATE   (5)
#define BIT_ADIF    (4)
#define BIT_ADIE    (3)
#define BIT_ADPS2   (2)
#define BIT_ADPS1   (1)
#define BIT_ADPS0   (0)

#define REG_ADCH     *((volatile uint8 *)0x25)

#define REG_ADCL     *((volatile uint8 *)0x24)

#define REG_TWDR     *((volatile uint8 *)0x23)

#define REG_TWAR     *((volatile uint8 *)0x22)
#define BIT_TWA6    (7)
#define BIT_TWA5    (6)
#define BIT_TWA4    (5)
#define BIT_TWA3    (4)
#define BIT_TWA2    (3)
#define BIT_TWA1    (2)
#define BIT_TWA0    (1)
#define BIT_TWGCE   (0)

#define REG_TWSR     *((volatile uint8 *)0x21)
#define BIT_TWS7    (7)
#define BIT_TWS6    (6)
#define BIT_TWS5    (5)
#define BIT_TWS4    (4)
#define BIT_TWS3    (3)
#define BIT_TWPS1   (1)
#define BIT_TWPS0   (0)

#define REG_TWBR     *((volatile uint8 *)0x20)

#endif /* REGISTER_MAP_H_ */
